### ISSUE TITLE
Error trying to use Ruby-lua

### ISSUE THREAD

**Issue by dejl** [glejeune/ruby-lua#2]
Hello,

When running ruby-luas example code i get:

.9.3p194 :034 > lua = Language::Lua.new()
dyld: lazy symbol binding failed: Symbol not found: _lua_newstate
  Referenced from: /Users/daniel/.rvm/gems/ruby-1.9.3-p194/gems/ruby-lua-0.3.0/lib/language/lua.bundle
  Expected in: flat namespace

dyld: Symbol not found: _lua_newstate
  Referenced from: /Users/daniel/.rvm/gems/ruby-1.9.3-p194/gems/ruby-lua-0.3.0/lib/language/lua.bundle
  Expected in: flat namespace

(irb):34: [BUG] Segmentation fault
ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-darwin11.4.2]

I have Lua and ruby installed + the gem..

**Comment by macbury** [comment]
I have this same problem

**Comment by glejeune** [comment]
Hum... Strange... What are you Lua (here 5.1.5) and Ruby (here 2.0.0p0) versions ?
